### ISSUE TITLE
[Feature Request] More parameters to customize 

### ISSUE THREAD

**Issue by Nico3652** [henryleunghk/flutter-native-text-input#10]
Thanks for the package. Please add more parameters for customization as we could set in the native code  : 

In my case, Tint color , Return Key , Capitalization... 

![Capture d’écran 2021-12-01 à 18 19 51](https://user-images.githubusercontent.com/50270977/144282417-5a83f1a3-598b-47b7-8cb7-c310de914c0f.png)

And from the CupertinoTextField :

- maxLines 
- suffix widget
- prefix widget

**Comment by henryleunghk** [comment]
Thanks for your support.

1. `cursorColor` will be added for UITextView tint color
2. `textCapitalization` will be added for controlling auto-capitalization
3. `returnKeyType` will be added inside a new iosOptions param
4. `maxLines` already available.
5. For `prefix` and `suffix`, will be regarded as out of scope. Please wrap them with `Row` widget in Flutter:)

**Comment by Nico3652** [comment]
Thanks for improvement.  Mistake about maxlines
