### ISSUE TITLE
[IMPROVEMENT]  Keyboard moving down/up when trying to keep focus 

### ISSUE THREAD

**Issue by Nico3652** [henryleunghk/flutter-native-text-input#24]
This method ```FocusScope.of(context).requestFocus(focusNode);```  to keep focus when I press 'action button'  make the keyboard moving down/up fast.  

I tried this code on the TextField & CupertinoTextField and I think this is working much better : 

" 
The cleanest approach would be to use onEditingComplete() with TextEditingController instead of onSubmitted(text). Refer below example.

```
  final _controller = TextEditingController();
  TextField(
       controller: _controller,
       padding: EdgeInsets.all(8),
       textInputAction: TextInputAction.send,
       placeholder: 'Type your message',
       onEditingComplete: (){
           if (_controller.text.isEmpty) return;

           sendMessage(_controller.text);
       },
  ),
```

"

Found on [stackOverFlow](https://stackoverflow.com/questions/55863766/how-to-prevent-keyboard-from-dismissing-on-pressing-submit-key-in-flutter).

Do you think you could try this with the native ?

**Comment by Tom3652** [comment]
This was actually the issue i had with the focus and that i have mentioned in the emoji size issue :)

**Comment by henryleunghk** [comment]
Dunno why the above example does not work on my side.
The cursor is still active but the keyboard is dismissed on pressing `done`/`send`.

But I would add support of `onEditingComplete?` then.
Thanks for your suggestion!
