### ISSUE TITLE
PlaceHolderStyle more useful than placeholderColor

### ISSUE THREAD

**Issue by Tom3652** [henryleunghk/flutter-native-text-input#27]
Hello and thanks for the updates on the package :) 

It was nice to be able to to set the ```placeholderStyle``` with a specific ```TextStyle```, rather than simply the color.  
Is it possible to have it back ? Or add a ```placeHolderFonts``` property for example ? (that would allow to set anything we want from TextStyle fonts (size, family...)

Thanks !

**Comment by henryleunghk** [comment]
Let me add them back to `iosOptions` then

**Comment by Tom3652** [comment]
Thanks :)
