### ISSUE TITLE
(controller , rebuild, focus ) issues

### ISSUE THREAD

**Issue by Hlebkuznetsov** [henryleunghk/flutter-native-text-input#41]
Hi,  thanks for the package !  
seems  like there is  couple of issues i found :
1)  when provide own controller,  its not  showing position of the  cursor (controller.selection.base.offset) always  show  -1 value 
2)  if return key set as DefaultValue, creation a new line will set the  cursor at the  end of the  text  length , despite  sometimes it  works  correctly , but in most cases behavior  is wrong (when try to create  a new line  somewhere in the  middle ).
3)  and the  last one :  rebuild  widget, which contains the Native Text Input widget not update the last one,   i mean  if there is any variable , which  change the  font size  , for example,  the build  method gets called. but value inside the  widget seems  not update  the  font  size.  despite  it changed   .

**Comment by randomhuangpl** [comment]
I foun when provide own controller in android,can't type more than one word 

@henryleunghk  Hi, thanks for this great package .Will this package continue update ?
