### ISSUE TITLE
Works also on the Text Widget

### ISSUE THREAD

**Issue by shinroketore** [henryleunghk/flutter-native-text-input#5]
im trying to achieve it also on Text Widget, planning to look like this:

![image](https://user-images.githubusercontent.com/21063638/124754856-5b1ebf80-df33-11eb-9a57-656fedcc8c9b.png)

its works only on the NativeTextInput but not on the Text Widget. Any idea how to make it work?

**Comment by henryleunghk** [comment]
Hmmm sorry, may your clarify what you want to achieve?

**Comment by henryleunghk** [comment]
So I guess you are talking about view mode.

Please refer to this:
https://github.com/henryleunghk/flutter-native-text-view
