### ISSUE TITLE
[Feature Request] Support Android native text field

### ISSUE THREAD

**Issue by ken-ng-esotec** [henryleunghk/flutter-native-text-input#9]
In order to gain popularity for this library, it would be great to extend support for Android text input. 

Do you foresee any challenges to include Android too?

**Comment by Tom3652** [comment]
Agree this would be awesome to be able to support Android as well

**Comment by henryleunghk** [comment]
Hmmm seems it worth doing so too as there are more feature for text selection using Android system textfield compared to Flutter one.
